version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: library_mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    
  backend:
    build: ./backend
    container_name: library_backend
    ports:
      - "3000:3000"
    environment:
        - MONGO_URI=mongodb://mongo:27017/library
        - PORT=3000
    depends_on:
        - mongo

  frontend:
    build: ./frontend
    container_name: library_frontend
    ports:
        - "5173:5173"
    environment:
        - VITE_BACKEND_URL=http://localhost:3000
    depends_on:
        - backend
    
volumes:
  mongo_data:
